//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Icon_spriteatlasv2
    {
        public const string BundleName = "icon_spriteatlasv2";
        public const string ICON = "Icon";
    }
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string ABILITYLEVELUP = "AbilityLevelUp";
        public const string ACHIEVEMENT = "Achievement";
        public const string BALL = "Ball";
        public const string BOMB = "Bomb";
        public const string BUTTONCLICK = "ButtonClick";
        public const string COIN = "Coin";
        public const string DIE = "Die";
        public const string ENEMYDIE = "EnemyDie";
        public const string EXP = "Exp";
        public const string GAMEPASS = "GamePass";
        public const string GETALLEXP = "GetAllExp";
        public const string HIT = "Hit";
        public const string HP = "HP";
        public const string HURT = "Hurt";
        public const string KNIFE = "Knife";
        public const string LEVELUP = "LevelUp";
        public const string TREASURECHEST = "TreasureChest";
        public const string WALK = "Walk";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
